<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_base"
 *
 * Auto generated by Extension Builder 2017-10-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'tollwerk Base',
    'description'      => 'Essentials and modern build tools and extensions for TYPO3 websites',
    'category'         => 'misc',
    'author'           => 'Joschi Kuphal',
    'author_email'     => 'joschi@tollwerk.de',
    'state'            => 'alpha',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '2.0.0',
    'constraints'      => [
        'depends'   => [
            'typo3' => '8.7.0-9.99.99',
        ],
        'conflicts' => [],
        'suggests'  => [],
    ],
];
